### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by kristiankielhofner** [toverainc/ai-router#2]
We will almost certainly use [TOML](https://github.com/toml-lang/toml). An example config file for ai-router.

```toml
# AI Router config
title = "ai-router example" # What would this be for?

# Our basic daemon config
[daemon] # Maybe ai-router?
instance_name = "my-ai-router" # I think this could be used for OpenTelemetry?
listen_ip = "192.168.0.1" # Could we do something like base_url from backends eg base_url "http://192.168.0.1:3000/v1"?
listen_port = 3000
base_path = "/v1" # OpenAI clients specify the base path with current version, could be interesting for multiple instances, different paths, etc. See URL syntax above. Could also move this to backends/models so people can use version as a hack to route to different backends/models/etc.
prompts_path = "./prompts" # For a directory of named prompt formats. See [models] below.
api_key = ["my_key", "another_key", "yet_another_key"] # basic support for multiple valid keys. Maybe also just takes a string when single key defined:
# api_key = "my_simple_key"
#api_key not defined - take anything from clients (wide open) - null, etc

# Triton/OpenAI backends
# Should support some large number in any reasonable configuration - 1024 or something
[backends]
# Something should probably go here, don't know yet
# Format is backends.[instance name].[function].[model]

[backends.my_triton_instance] # No idea if this is valid, the second value is name for model/function routing below
type = "triton" # from backends source dir/defined name
base_url = "http://my.triton.host.or.ip:8001" # Doesn't really make sense for Triton but for syntax compatibility with OpenAI backend models or interesting load balancing, who knows what scenarios
mode = "grpc" #optional/no current plans to support HTTP. Could also be "protocol" or something...
default = true # Use this backend if not overridden specifically with backend/model/path eg just pass everything to backend, etc if not specified

[backends.openai] # No idea if this is valid, the second value is name for model/function routing below.
type = "openai" # from backends source dir/defined name
base_url = "https://api.openai.com/v1" # default to OpenAI
default = false # Use this backend if not overridden specifically with model/path
api_key = "my_openai_api_key" # Allow different backend names with different keys, routing models/type to different OpenAI keys for example

[backends.openai_azure] # No idea if this is valid, the second value is name for model/function routing below.
# Azure docs: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions
type = "openai" # from backends source dir/defined name
base_url = "https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/completions?api-version={api-version}" # WTF Azure, need to figure out how clients do this
api_key = "my_azure_openai_api_key" # Allow different backends with different keys, routing models/type to different OpenAI keys # Need to figure out how Azure does this...
your_resource_name = "see_azure_docs" # Optional, not included by default
deployment_id = "see_azure_docs" # Optional, not included by default
api_version = "see_azure_docs" # Optional, not included by default
# The three fields above may not be necessary, never used OpenAI Azure endpoints but will either need to set it up or find someone who does to test

[backends.vllm] # No idea if this is valid, the second value is name for model/function routing below
type = "openai" # from backends source dir/defined name
base_url = "http://192.168.0.5:8000/v1" # vLLM default
default = false # Don't use this backend if not overridden specifically with function/model
api_key = "EMPTY" # This is vLLM default

# HF TEI example
[backends.hf_tei] # No idea if this is valid, the second value is name for model/function routing below
type = "openai" # from backends source dir/defined name
base_url = "http://192.168.0.5:8000/v1"
default = false # Don't use this backend if not overridden specifically with function/model
dimensions = 1024 # Not sure if this is necessary
max_input = 512 # We need to return error if using the default OpenAI client that supports larger size for their models

[backends.hf_tgi] # No idea if this is valid, the second value is name for model/function routing below
type = "openai" # from backends source dir/defined name
base_url = "http://192.168.0.5:8000/v1"
default = false # Don't use this backend if not overridden specifically with function/model
api_key = "EMPTY" # I think TGI takes anything by default IIRC

[backends.weird_map_name_to_something] # No idea if this is valid, the second value is name for model/function routing below
type = "openai" # from backends source dir/defined name
base_url = "https://api.openai.com/v1" # default to OpenAI
default = false # Don't use this backend if not overridden specifically with function/model
api_key = "my_openai_key"

[models]
# Should support some large number in any reasonable configuration - 1024 or something
# Middle 2-3 is based on OpenAI function/path from https://platform.openai.com/docs/api-reference
# Basically take the OpenAI API base and change the / to . for TOML?
# Need to really think about this

# Chat completions
[models.chat.completions.Mistral-7B-Instruct-v0.2] # No idea if this will be valid, also needs to support at least "/" eg mistral/Mistral-7B-Instruct-v0.2 because that's what vLLM, etc do especially when loading from HF hub
backend = "my_triton_instance"
backend_model = "some_other_name_in_triton" # Not sure about this but gets interesting to map eg gpt-* to some other name in triton, your own OpenAI API compliant backend, etc
prompt_format = "mistral" # Loaded from prompts_path (./prompts/mistral.some_format) above to do eg '<s>[INST] {input} [/INST]'. Prompt formatting gets tricky, need to figure out how to handle OpenAI client roles, etc to support any backend model prompt format while maintaining transparent OpenAI client compatibility. Possibly "just" a TOML include?
default = true # Take any client defined input model (gpt*) and just route the request to this model so eg they can send OpenAI default model names from official client. Can only be defined once per models.chat.completions. type
max_input = 32768 # Default for Mistral, we need to return error if input from client is larger

# embeddings
[models.embeddings.bge-large-en-v1.5]
backend = "my_triton_instance"
backend_model = "bge-large-en-v1.5"
dimensions = 1024 # Not sure if this is necessary
default = true
max_input = 512 # We need to return error if using the default OpenAI client that supports larger size for their models

# OpenAI example
# embeddings
[models.embeddings.text-embedding-ada-002]
backend = "openai"
backend_model = "text-embedding-ada-002" # Default to the name/path


```

Very aspirational, needs to be validated for rust and TOML validity, I'm sure I messed a few things up/forgot some stuff.
